rsync -a ./.zshrc ~/.config
rsync -a ./nvim ~/.config
rsync -a ./helix ~/.config
rsync -a ./wezterm ~/.config
rsync -a ./lazygit ~/.config
rsync -a ./borders ~/.config
rsync -a ./Brewfile ~/.config
rsync -a ./starship.toml ~/.config
rsync -a ./yazi ~/.config
rsync -a ./zk ~/.config
rsync -a ./aerospace ~/.config
rsync -a ./mise ~/.config
