[tools]
deno = "latest"
go = "1"
node = "22.18.0"
"npm:@tailwindcss/language-server" = "0.14.26"
"npm:@vue/language-server" = "2.2.12"
"npm:typescript" = "5.9.2"
"npm:typescript-language-server" = "4.4.0"
"npm:vscode-langservers-extracted" = "4.10.0"
